version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: install npm dependencies
          command: npm install

      - run:
          name: run prettier
          command: npm run prettier:check

      - run:
          name: run lint
          command: npm run lint

      - run:
          name: run tests with coverage
          command: npm run test:coverage

      - run:
          name: upload coverage to coveralls
          command: |
            sudo npm install -g coveralls
            cat ./coverage/lcov.info | coveralls

workflows:
  version: 2
  client_build:
    jobs:
      - build
