import type { Metadata } from 'next';
<<<<<<< HEAD
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
import { Roboto, Rubik } from 'next/font/google';

import './globals.scss';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

const rubik = Rubik({
  weight: ['700'],
  style: ['normal'],
  subsets: ['latin'],
  fallback: ['Roboto', 'Arial', 'sans-serif'],
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: 'E-Healthy',
  description: 'Portal dedicado ao cuidado da saúde mental.',
>>>>>>> c2e6b50bc7d80129c2c04d3bd05c44a83314a924
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classes = `${roboto.variable} ${rubik.variable}`;
  return (
    <html lang="pt-br">
      <body className={classes}>{children}</body>
    </html>
  );
}
