name: build

on:
  push:
    branches: [main]
    paths:
      - 'client/**'

env:
  CI: true

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./client/coverage/lcov.info
          base-path: ./client
