name: Lighthouse CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://e-healthy-client.vercel.app/
          budgetPath: ../budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
